adminbase/urls.py
from django.conf.urls import include, url
from django.contrib import admin


app_name = "adminbase"
urlpatterns = [
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^', include('game.urls', namespace='game')),
    url(r'^', include('messenger.urls', namespace='messenger')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url
from . import views


app_name = "dashboard"
urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name="login"),
    url(r'^login$', views.LoginView.login, name="login"),
    url(r'^logout$', views.LoginView.logout, name="login"),
    url(r'^room_management/$', views.RoomManagementView.as_view(), name='room_management'),
    url(r'^new_room/$', views.NewRoomView.as_view(), name="new_room"),
    url(r'^data/$', views.DataView.as_view(), name="data"),
    url(r'^logs/$', views.LogsView.as_view(), name="logs"),
]

game/urls.py
from django.conf.urls import url
from . import views


app_name = "game"
urlpatterns = [
    url(r'^client_request/$', views.client_request),
    url(r'^duopoly-admin/client_request/$', views.client_request),
]

messenger/urls.py
from django.conf.urls import url
from . import views


app_name = "messenger"
urlpatterns = [
    url(r'^duopoly-admin/messenger/$', views.MessengerClientSide.messenger),
    url(r'^messenger/$', views.MessengerClientSide.messenger),
    url(r'^messenger_view/$', views.MessengerView.as_view(), name='messenger_view'),
    url(r'^refresh_messenger/$', views.MessengerView.as_view())
]

messenger/models.py
from django.db import models


class Message(models.Model):

    author = models.TextField(db_index=True, max_length=30, default="null")
    to = models.TextField(db_index=True, max_length=30, default="null")
    message = models.TextField()
    time_stamp = models.DateTimeField(auto_now_add=True, blank=True)
    receipt_confirmation = models.BooleanField(db_index=True, default=False)


class BoolParameter(models.Model):

    name = models.TextField()
    value = models.BooleanField(default=False)


class DateTimeParameter(models.Model):

    name = models.TextField()
    value = models.DateTimeField(auto_now_add=True, blank=True)


class IntParameter(models.Model):

    name = models.TextField()
    value = models.IntegerField()
    unit = models.TextField()

messenger/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
import os

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

import game.user.messenger

from utils import utils
from . import management

__path__ = os.path.relpath(__file__)


@method_decorator(login_required, name='dispatch')
class MessengerView(TemplateView):

    template_name = "components/messenger.html"
    user = None

    def get_context_data(self, **kwargs):

        """
        Last method to be called.
        Updates the context
        with current info.
        """

        context = super().get_context_data(**kwargs)

        # Set titles of the page
        context.update({'subtitle': "Chat with players"})

        # Update connected players
        game.user.messenger.check_connected_users()

        # Get messages
        users = management.get_all_users()
        # update context with users
        context.update({"users": users})
        # Get slide auto_reply value
        auto_reply = management.get_auto_reply()
        # update context with auto_reply
        context.update({"auto_reply": auto_reply})

        management.set_user_msg_as_read(self.user)

        context.update(
            {"current_user": self.user}
        )

        # update context with messages
        messages = management.get_all_messages_from_user(context['current_user'])

        # reload = any(not m.receipt_confirmation for m in messages)
        context.update({'messages': messages})
        # context.update({'reload': reload})

        return context

    def dispatch(self, request, *args, **kwargs):

        """
        Dispatch is the first method to be called.
        After checking the url for a user selected, and
        checking the post data (to see if a msg is submitted)
        let the TemplateView do its stuff (get_context_data...)
        """

        # If it is an "auto_reply" setting request
        if "auto_reply" in request.GET:
            management.set_auto_reply(int(request.GET["auto_reply"]))
            return HttpResponse("Auto reply set.")

        # Then select user based on user_id
        # If user_id is None, redirect to last msg user
        if "user_id" in request.GET:

            user_id = request.GET["user_id"]

            if user_id != "null":
                self.user = management.get_user_from_id(int(user_id))

        elif "user" in request.POST:
            pass

        else:
            last_author = management.get_latest_msg_author()
            if last_author:
                return redirect('/messenger_view/?user_id={}'.format(last_author.id))
            else:
                self.user = None

        # REFRESH REQUESTS
        # There are different type of refresh request
        # msg -> refresh all msg from the selects user
        # contacts -> refresh contact list and their attributes
        # all_unread_msg -> refresh the msg counter (located on the sidebar)
        if "type" in request.GET:

            if management.has_to_refresh():

                management.set_time_last_refresh()

                if request.GET["type"] == "msg":
                    return self.refresh_msg(request, **kwargs)

                elif request.GET["type"] == "contacts":
                    return self.refresh_contacts(request, **kwargs)

                elif request.GET["type"] == "all_unread_msg":
                    return self.refresh_all_unread_msg(request, **kwargs)
            else:

                return JsonResponse({"refresh": False})

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):

        """
        used when sending a msg
        """
        username = request.POST["user"]
        management.send_message(username=username, message=request.POST["msg"])

        return HttpResponse("Sent!")

    def refresh_msg(self, request, **kwargs):

        new_from_user = management.get_unread_msg(self.user) > 0
        new_from_admin = management.get_unread_msg("admin") > 0

        if new_from_admin or new_from_user:
            context = {
                "messages": management.get_all_messages_from_user(self.user),
                "current_user": self.user,
                "scroll": int(new_from_user)
            }
            management.set_user_msg_as_read(self.user)
            return render(request, MessengerRefreshView.msg_template_name, context)

        else:
            return JsonResponse({"refresh": False})

    def refresh_contacts(self, request, **kwargs):

        # Update connected players
        game.user.messenger.check_connected_users()

        context = {
            "users": management.get_all_users(),
            "current_user": self.user,
        }

        return render(request, MessengerRefreshView.contact_template_name, context)

    @staticmethod
    def refresh_all_unread_msg(request, **kwargs):
        return JsonResponse({"count": management.get_unread_msg()})


class MessengerRefreshView(TemplateView):
    msg_template_name = "components/msg_refresh.html"
    contact_template_name = "components/contact_refresh.html"


class MessengerClientSide:

    @classmethod
    @csrf_exempt
    def messenger(cls, request):
        demand = request.POST["demand"]

        # retrieve method
        command = getattr(cls, demand)

        to_reply = "/".join((str(i) for i in command(request)))

        response = HttpResponse(to_reply)
        response["Access-Control-Allow-Credentials"] = "true"
        response["Access-Control-Allow-Headers"] = "Accept, X-Access-Token, X-Application-Name, X-Request-Sent-Time"
        response["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
        response["Access-Control-Allow-Origin"] = "*"
        return response

        # ----------- Demand relatives to messenger --------------- #

    @classmethod
    def client_speaks(cls, request):

        username = request.POST["username"].lower()
        message = request.POST["message"]

        management.new_message_from_client(username=username, message=message)

        return "reply", "done"

    @classmethod
    def client_hears(cls, request):

        username = request.POST["username"].lower()

        n_new_messages, new_messages = management.get_messages_for_client(username=username)

        return ("reply", n_new_messages,) + tuple((i for i in new_messages))

    @classmethod
    def client_receipt_confirmation(cls, request):

        username = request.POST["username"].lower()
        messages_list = request.POST["message"]
        messages = [i for i in messages_list.split("/") if len(i)]

        management.receipt_confirmation_from_client(username, messages)

        return "reply", "done."

templates/components/contact_refresh.html
 <tbody>
    {% for user in users %}
        <tr onclick="ClickedOnContact({{ user.id }})" oncontextmenu="OpenProfileTab({{ user.id }})">
            <td>
               {% if user.connected %}
                    <span class="fa fa-circle" style="color: #3F903F; font-size: 9px;"></span>
                {% else %}
                    <span class="fa fa-circle" style="color: #a94442; font-size: 9px;"></span>
                {% endif %}
                {{ user.username }}
                {% if user.n_unread %}
                        <a id="label_n_unread" class="label" style="font-size: 14px; float: right;">{{ user.n_unread }}</a>
                {% endif %}
                <br>
                {% if user.room_id %}
                <a id="label_progression" class="label" style="background-color: #F4821C;">room {{ user.room_id }}</a>
                {% endif %}
                {% if user.state %}
                <a id="label_state" class="label">{{ user.state }}</a>
                    {% if user.state != "end" %}
                        <a id="label_progression" class="label">{{ user.progression }}%</a>
                    {% endif %}
                {% endif %}
                {% if user.deserter == 1 %}
                    <a id="label_state" class="label" style="background-color: black;">banned</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
        <tr>
        <td style="background-color: #FFFFFF"></td>
        </tr>

</tbody>

templates/components/data.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block page_content %}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{{  title }}</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                {{  subtitle }}
            </div>
            <br>
            <br>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6 col-lg-offset-3" align="center">
{#                        <a class="btn btn-info"#}
{#                           href="{% static url_pickle %}" download><i class="fa fa-download"></i> Download pickle data</a>#}
{#                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/SQLite370.svg/2000px-SQLite370.svg.png"#}
{#                            style="width: 20%">#}
                        <a class="btn btn-danger" onclick="flushDB();"><i class="fa fa-remove"></i> Flush DB</a>
                        <a class="btn btn-success" style="margin-left: 8px;"
                           onclick="getDatabaseURL();" download><i class="fa fa-download"></i> SQLite data</a>
                        <br>
                        <br>
                        <br>
                        <div class="progress" style="display: none;" id="progressdiv" hidden>
                            <div id="progressbar" class="progress-bar progress-bar-striped active" role="progressbar"
                                 aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                            </div>
                        </div>
{#                        <img id="done" src="/static/admin/img/icon-yes.svg" style="width: 30px;" hidden>#}
                        <br>
                        <br>

                    </div>
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
</div>
<!-- /.row -->
    <script>

    function getDatabaseURL() {

        $("#progressbar").addClass("active");
        $("#progressbar").text("");
        $("#progressdiv").hide();
        $("#progressdiv").show();

        $.ajax({
            method: "GET",
            url: "/data/?sqlite=true",
            success: function (data) {
                downloadDB(data["url"]);
                $("#progressbar").text("Conversion done!");
                $("#progressbar").removeClass("active");
            }
        })
    }

    function flushDB () {
        $("#progressbar").addClass("active");
        $("#progressbar").text("");
        $("#progressdiv").hide();
        $("#progressdiv").show();

        $.ajax({
            method: "GET",
            url: "/data/?flush=true",
            success: function () {
                console.log("Flushed!");
                $("#progressbar").text("Database flushed!");
                $("#progressbar").removeClass("active");
            }
        });

    }

    function downloadDB(url) {
        var link = document.createElement("a");
        link.href = "/static/" + url;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }

    </script>

{% endblock page_content %}

templates/components/login.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block basecontent %}

{% if user.is_authenticated %}
    <script>
    window.location = "/room_management/";
    </script>
{% endif %}

<div class="container">
    <div align="middle" >
        <img src="{% static 'img/duopoly.png' %}" align="middle" style="width: 25%; height: 25%">
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body" >
                    <form role="form" action="login" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="Username" name="username" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <button class="btn btn-lg btn-success btn-block">Login</button>
                        </fieldset>
                    </form>
                    <hr>
                    {%  if fail %}
                       <div class="alert alert-danger">
                           <strong>Error:</strong>  Wrong username or password.
                        </div>
                    {%  endif %}
                </div>
            </div>
        </div>
    </div>
</div>
    
{% endblock basecontent %}

templates/components/logs.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block page_content %}


    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{  title }}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{  subtitle }}
                </div>
                <br>
                <br>
                <div class="panel-body">
                    <div class="row">
                        <div style="margin-bottom: 5px; margin-left: 15px">
                            <button class="btn btn-success" onclick="Start();">Start</button>
                            <button class="btn btn-danger" onclick="Stop();">Stop</button>
                        <div style="margin-right: 15px" align="right">
                            <select id="logfile" onchange="GoToFileName(this);" class="form-control" style="width: 20%;">
                                {% for file in files %}
                                    {% if current_file == file %}
                                        <option value="{{ file }}" selected>{{ file }}</option>
                                    {% else %}
                                        <option value="{{ file }}">{{ file }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        </div>
                       <pre id="logs">
                           {{ logs }}
                       </pre>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    <!-- /.row -->
    <script>

    var refresh = true;
    var logs = document.getElementById("logs");

    ScrollToBottom();
    setInterval(RefreshLogs, 1000);

    function GoToFileName(element) {
        var filename = element.options[element.selectedIndex].text;
        Start();
        RefreshLogs(filename, 0);
    }

    function Stop () {
        refresh = false;

    }

    function Start () {
        refresh = true;

    }

    function RefreshLogs(filename, n_lines) {

        if (refresh) {

            if (filename === undefined ) {
                filename = $("#logfile").find(":selected").text();
            }

            if (n_lines === undefined) {
                 n_lines = $("#logs").text().split("\n").length;
            }

            $.ajax({
                type: "GET",
                url: '/logs/?refresh_logs=1&filename=' + filename + '&n_lines=' + n_lines,
                success: function (data) {
                    if (data["logs"].length > 0) {

                       //if (n_lines === 0) {
                        $('#logs').html(data["logs"]);
                        //} else {
                         //   $('#logs').append(data["logs"]);
                        //}
                    }
                    ScrollToBottom();
                }

            });
        }
    }


    function ScrollToBottom() {
         // Make the scrollbar go down
         logs.scrollTop = logs.scrollHeight;
    }

    </script>

{% endblock page_content %}

templates/components/msg_refresh.html
{% load staticfiles %}
{% for msg in messages %}
<!-- display admin msg ----->
{% if msg.author == "admin" %}
<div class="row msg_container base_sent">
    <div class="col-md-10 col-xs-10" align="right">
                <div class="messages msg_sent" style="display: inline-block;">
                    <p> {{ msg.message }}</p><br>
                    {% if msg.receipt_confirmation %}
                        <a style="font-size: 10px"> ✔ {{ msg.time_stamp }}</a>
                    {% endif %}
                </div>
    </div>
</div>
{% endif  %}
<!-- display user msg ----->
{% if msg.author == current_user %}
<div class="row msg_container base_receive">
    <div class="col-md-10 col-xs-10">
        <div class="messages msg_receive" style="display: inline-block; margin-left: 10px">
            <p> {{ msg.message }}</p><br>
            {% if msg.receipt_confirmation %}
                <a style="font-size: 10px">{{ msg.time_stamp }}</a>
            {% endif %}
        </div>
    </div>
</div>
{% endif  %}
{% endfor %}

<!-- If true scroll down messages -->
<input id="scroll" value="{{ scroll }}"  hidden>

templates/components/room_management.html
{% extends "dashboard/base.html" %}
{% block page_content %}

<script>
// set room_management tab active if coming from new_room
if (document.referrer.indexOf("new_room") !== -1){
    SetTabActive();
}
</script>

    <!-- Modal pop up window used in order to inform that -->
    <div class="modal fade" id="myModal" role="dialog">
        <input style="display: none;" id="roomToDelete" value="">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header" align="middle">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <span class="fa fa-remove" style="font-size: 50px; color: #D9534F;"></span>
                    <h4 class="modal-title"> Warning! </h4>
                </div>
                <div class="modal-body">
                    <p> Do you want to delete this room? </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-alert" onclick="DeleteRoom($('#roomToDelete').val())">Delete</button>
                </div>
            </div>
        </div>
    </div>

    <!--------- /Modal  -->
    <div class="row">
        <div class="col-lg-12">
                <h1 class="page-header"> {{ title }}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ subtitle }}
                </div>
                <div class="panel-body">
                    <div class="row">
                            <div align="middle" style="margin-right: 200px; margin-left: 200px; margin-top: 100px;">

                                <div class="panel-group">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" data-toggle="collapse" href="#collapse-info"
                                        style="cursor: pointer;">
                                            <h4 class="panel-title">
                                                <a style="font-size: 22px; pointer-events: none; cursor: default;">General information</a>
                                            </h4>
                                        </div>
                                    <div id="collapse-info" class="panel-collapse collapse" align="middle">
                                        <ul class="list-group">
                                            <li class="list-group-item">
                                                <strong>Number of 0.25 rooms with opp score (opened/completed):</strong> {{ room_info.room_25_opp_score }}
                                                <br>
                                                <strong>Number of 0.25 rooms without opp score (opened/completed):</strong> {{ room_info.room_25_no_opp_score }}
                                                <br>
                                                <strong>Number of 0.50 rooms with opp score (opened/completed):</strong> {{ room_info.room_50_opp_score }}
                                                <br>
                                                <strong>Number of 0.50 rooms without opp score (opened/completed):</strong> {{ room_info.room_50_no_opp_score }}
                                                <br>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                </div>
                            {% for room in rooms %}
                               <div class="panel-group">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" data-toggle="collapse" href="#collapse{{ room.att.id }}"
                                        style="cursor: pointer;">
                                            <h4 class="panel-title">
                                                <a style="font-size: 22px; pointer-events: none; cursor: default;">Room {{ room.att.id }}</a>
                                            </h4>
                                        </div>
                                    <div id="collapse{{ room.att.id }}" class="panel-collapse collapse" align="middle">
                                        <ul class="list-group">
                                            <li class="list-group-item">
                                                <h4>Properties</h4>
                                                {% if room.att.opened %}
                                                    <strong> Opened: </strong> <img src="/static/admin/img/icon-yes.svg" alt="True">
                                                {% else %}
                                                    <strong> Opened: </strong> <img src="/static/admin/img/icon-no.svg" alt="False">
                                                {% endif %}
                                                <br>
                                                <strong> Missing players: </strong>{{ room.att.missing_players }}
                                                <br>
                                                <strong> Field of view radius: </strong>{{ room.att.radius }}
                                                <br>
                                                {% if room.att.trial %}
                                                    <strong> Trial: </strong> <img src="/static/admin/img/icon-yes.svg" alt="True">
                                                {% else %}
                                                    <strong> Trial: </strong> <img src="/static/admin/img/icon-no.svg" alt="False">
                                                {% endif %}
                                                <br>
                                                {% if room.att.display_opponent_score %}
                                                    <strong> Display opponent score: </strong><img src="/static/admin/img/icon-yes.svg" alt="True">
                                                {% else %}
                                                    <strong> Display opponent score: </strong> <img src="/static/admin/img/icon-no.svg" alt="False">
                                                {% endif %}
                                                <br>
                                                <strong> State: </strong>{{ room.att.state }}
                                                <br>
                                                <br>
                                            </li>
                                            <li class="list-group-item">
                                                <h4>Connected players</h4>
                                                    {% for player in room.connected_players %}
                                                        {% if player %}

                                                            {% if player.deserter == 1 %}
                                                                <i class="fa fa-circle" style="color: #0f0f0f"></i>
                                                            {% elif player.connected == 1%}
                                                                <i class="fa fa-circle" style="color: #5CB85C"></i>
                                                            {% else %}
                                                                <i class="fa fa-circle" style="color: #D9534F"></i>
                                                            {% endif %}

                                                            <strong>{{ player.username }}</strong>
                                                            in state <strong>{{ player.state }}</strong>
                                                            with last request <strong>{{ player.last_request }}</strong>
                                                            at time <strong>{{ player.time_last_request }}</strong>

                                                            <br>
                                                        {% endif %}
                                                    {% endfor %}
                                            </li>
                                        </ul>

                                    <div class="panel-footer">
                                            <!-- Delete room button -->
                                            <form id="delete-room-{{ room.att.id }}" action="" method="post">
                                                {% csrf_token %}
                                                <input type="text" style="display: none;" name= "delete" value="{{ room.att.id }}">
                                            </form>
                                            <button onclick="ShowModal({{ room.att.id }})" class="btn btn-danger">Delete room {{ room.att.id }}</button>

                                    </div>
                                    </div>
                                    </div>
                                    </div>
                            {% endfor %}

                            <form action="{% url 'dashboard:new_room' %}" method="get" style="margin-top: 100px;">
                                <button class="btn btn-success" style="font-size: 20px; display: table-cell;"><span
                                        class="fa fa-plus"></span></button>
                            </form>
{#                            Add a room#}
                        </div>

                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            <!-- /.col-lg-12 -->
        </div>

    <script>
    function ShowModal(room_id) {
        $("#roomToDelete").val(room_id);
        $('#myModal').modal();

    }

    function DeleteRoom(room_id) {
        document.getElementById("delete-room-" + room_id).submit()
    }

    function SetTabActive(){
        document.getElementById("room_management_tab").setAttribute("class", "active")
    }
    </script>

{% endblock page_content %}
</div>