adminbase/urls.py
from django.conf.urls import include, url
from django.contrib import admin


app_name = "adminbase"
urlpatterns = [
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^', include('game.urls', namespace='game')),
    url(r'^', include('messenger.urls', namespace='messenger')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url
from . import views


app_name = "dashboard"
urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name="login"),
    url(r'^login$', views.LoginView.login, name="login"),
    url(r'^logout$', views.LoginView.logout, name="login"),
    url(r'^room_management/$', views.RoomManagementView.as_view(), name='room_management'),
    url(r'^new_room/$', views.NewRoomView.as_view(), name="new_room"),
    url(r'^data/$', views.DataView.as_view(), name="data"),
    url(r'^logs/$', views.LogsView.as_view(), name="logs"),
]

game/urls.py
from django.conf.urls import url
from . import views


app_name = "game"
urlpatterns = [
    url(r'^client_request/$', views.client_request),
    url(r'^duopoly-admin/client_request/$', views.client_request),
]

messenger/urls.py
from django.conf.urls import url
from . import views


app_name = "messenger"
urlpatterns = [
    url(r'^duopoly-admin/messenger/$', views.MessengerClientSide.messenger),
    url(r'^messenger/$', views.MessengerClientSide.messenger),
    url(r'^messenger_view/$', views.MessengerView.as_view(), name='messenger_view'),
    url(r'^refresh_messenger/$', views.MessengerView.as_view())
]

dashboard/models.py
from django.db import models


class IntParameter(models.Model):

    name = models.TextField()
    value = models.IntegerField()
    unit = models.TextField()

dashboard/forms.py
from django import forms

from crispy_forms.bootstrap import Field, Accordion, AccordionGroup
from crispy_forms.helper import FormHelper


class ParametersForm(forms.Form):

    class Meta:
        abstract = True

    error_css_class = 'has-error'

    nb_of_room = forms.IntegerField(
        label="Number of room",
        initial=1,
        required=True
    )

    ending_t = forms.IntegerField(
        label="Duration",
        required=True,
        initial=25,
    )

    radius = forms.ChoiceField(
        widget=forms.Select,
        choices=[
            (0.25, '0.25'),
            (0.5, '0.50'),
            (0.75, '0.75'),
            (1., '1.00'),
        ],
        label="Field of view radius for consumers",
        required=True
    )

    trial = forms.BooleanField(
        label="Trial",
        initial=False,
        required=False,
    )

    display_opponent_score = forms.BooleanField(
        label="Display opponent score",
        initial=False,
        required=False
    )

    form_function = forms.Field(widget=forms.HiddenInput, initial="room_organisation")


class RoomForm(ParametersForm):

    def __init__(self, *args):

        super(RoomForm, self).__init__(*args)

        self.helper = FormHelper()
        self.helper.form_tag = False

        self.group = (Field(field) for field in self.fields)

        self.helper.layout = Accordion(
            AccordionGroup('Parameters', *self.group),
        )

        self.cleaned_data = None

    def clean(self):

        """
        called by is_valid method
        when the form is going
        to be validated
        """

        self.cleaned_data = super(RoomForm, self).clean()

        cleaned_data = self.cleaned_data.copy()

        if cleaned_data.get("trial") is None:
            self.cleaned_data["trial"] = False
            self.cleaned_data["display_opponent_score"] = False
        else:
            cleaned_data.pop("trial")
            cleaned_data.pop("display_opponent_score")

        if not all(cleaned_data.get(field) for field in cleaned_data.keys()):

            raise forms.ValidationError(
                message="You must fill in all the required fields!",
            )

    def get_data(self):

        return self.cleaned_data

dashboard/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.gzip import gzip_page
from django.db import transaction
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
import os

from . forms import RoomForm
# from utils import utils

from parameters import parameters

import game.room.dashboard
import game.user.dashboard


class LoginView(TemplateView):

    template_name = "components/login.html"

    def get_context_data(self, **kwargs):

        context = super(LoginView, self).get_context_data(**kwargs)

        return context

    @classmethod
    def login(cls, request):

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            # utils.log("Logging {} user.".format(user), f=login)
            login(request, user)
            return redirect("/room_management/")

        else:
            return render(request, cls.template_name, {"fail": 1})

    @classmethod
    def logout(cls, request):

        logout(request)
        return redirect("/")


@method_decorator(login_required, name='dispatch')
class NewRoomView(TemplateView):

    template_name = "components/new_room.html"

    def get_context_data(self, **kwargs):

        context = super(NewRoomView, self).get_context_data(**kwargs)
        context.update({"subtitle": "Set parameters and create a room"})
        form = RoomForm()

        context.update({'form': form})

        return context

    @transaction.atomic
    def post(self, request, *args, **kwargs):

        """
        Room creation process
        :param request: using POST request
        :return: html room form template (success or fail)
        """

        if request.POST["form_function"] == "room_organisation":

            form = RoomForm(request.POST)

            if form.is_valid():

                with transaction.atomic():
                    # Create room
                    game.room.dashboard.create(form.get_data())

                return redirect("/room_management")

            else:
                context = {"subtitle": "Set parameters and create a room", "form": form}
                return render(request, self.template_name, context)

        else:
            raise Exception("Error validating the form.")


@method_decorator(login_required, name='dispatch')
class RoomManagementView(TemplateView):

    template_name = "components/room_management.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context.update({'subtitle': "Room list"})

        # check connected users
        game.user.dashboard.check_connected_users()

        # Get list of existing rooms and players
        rooms_list = game.room.dashboard.get_list()

        room_info = game.room.dashboard.get_rooms()

        context["room_info"] = room_info

        context.update({"rooms": rooms_list})

        return context

    def post(self, request, *args, **kwargs):

        if "delete" in request.POST:
            room_id = request.POST["delete"]
            # utils.log("Delete room {}.".format(room_id), f=self.post)

            # Delete room
            game.room.dashboard.delete(room_id=room_id)

        return redirect("/room_management")


@method_decorator(login_required, name='dispatch')
class DataView(TemplateView):
    template_name = "components/data.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context.update({"subtitle": "Download data"})
        return context

    def dispatch(self, request, *args, **kwargs):

        if "sqlite" in request.GET:
            return self.convert_data_to_sqlite()

        if "flush" in request.GET:
            game.room.dashboard.flush_db()

        return super().dispatch(request, *args, **kwargs)

    @staticmethod
    def convert_data_to_sqlite():

        url = game.room.dashboard.convert_data_to_sqlite()
        return JsonResponse({"url": url})


@method_decorator(gzip_page, name='dispatch')
@method_decorator(login_required, name='dispatch')
class LogsView(TemplateView):
    template_name = "components/logs.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context.update({"subtitle": "Logs"})

        if os.path.exists(parameters.logs_path):
            files = sorted(
                [f for f in os.listdir(parameters.logs_path)
                 if os.path.isfile("".join([parameters.logs_path, f]))]
            )
        else:
            files = []

        current_file = files[-1]
        context.update({"current_file": current_file})
        context.update({"logs": self.refresh_logs(current_file)})
        context.update({"files": files})

        return context

    def dispatch(self, request, *args, **kwargs):

        if "refresh_logs" in request.GET:
            if request.GET["refresh_logs"]:

                filename = request.GET["filename"]
                n_lines = int(request.GET["n_lines"])

                return JsonResponse(
                    {
                        "logs": self.refresh_logs(filename, n_lines)
                     }
                )

        return super().dispatch(request, *args, **kwargs)

    @staticmethod
    def refresh_logs(filename, n_lines=None):

        f = parameters.logs_path + filename
        if os.path.exists(f):
            with open(parameters.logs_path + filename, "r") as f:
                # if n_lines:
                logs = "".join(f.readlines()[-500:])
                # else:
                #     logs = f.read()
            return logs

templates/dashboard/base.html
{% extends "layout/base.html" %}
{%  load staticfiles %}

{% block basecontent %}
<div id="wrapper">
        <a class="navbar-brand" href="/" style="color: #abb9d3;">
            Duopoly Experiment</a>
        <br>
        <br>

        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation" style="background-color: #343A40; border-color: #343A40;">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <img src="{% static 'img/heidegger.jpg' %}"
                         class="img-responsive" style="border: 2px solid #d4d4d4; width:
                         140px;margin-left: 50px;margin-top: 40px;" >
                    <br>
                    <a href="/logout" ><i class="fa fa-sign-out" style="margin-left: 83px; font-size: 15px;
                     font-family: FontAwesome, sans-serif;">Logout</i></a>
                    <br>
                    <br>
                    <br>
                    <li>
                    <a id="room_management_tab" href="{% url 'dashboard:room_management' %}">
                        <i class="fa fa-group fa-fw"></i> Room management</a>
                    </li>
                    <li>
                        <a href="{% url 'messenger:messenger_view' %}"><i class="fa fa-comments fa-fw"></i> Chat
                            <span id="label_n_unread"
                               style="visibility: hidden; display: inline;
                                margin-left: 60%; font-weight: bold; padding: 5px; border-radius: 2px;"></span></a>
                    </li>
                    <li>
                        <a href="{% url 'admin:index' %}"><i class="fa fa-table fa-fw"></i> Tables</a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:data' %}"><i class="fa fa-line-chart fa-fw"></i> Data</a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:logs' %}"><i class="fa fa-file-text fa-fw"></i> Logs</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
</div>

    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 1500px">
    <div class="fadeIn">
        {% block page_content %}
        {% endblock page_content %}
    </div>
    </div>
    <!-- /#page-wrapper -->
<!-- /#wrapper -->
    <script>

    setInterval(RefreshMsgUnreadCount, 3000);

    function RefreshMsgUnreadCount(){
        if (!window.location.href.match("messenger")) {
            $.ajax({
                type: "GET",
                url: '/refresh_messenger/?user_id=null&type=all_unread_msg',
                success: function (data) {
                    var label = document.getElementById("label_n_unread");
                    // REFRESH sidebar
                    if (data["count"] > 0){
                        label.innerHTML = data["count"];
                        label.style.visibility = "visible";
                        console.log(data["count"]);
                    }
                    else{
                        console.log("do not display");
                        label.style.visibility = "hidden";
                    }

                }

            });
        }
    }

    </script>

{% endblock basecontent %}